# N_6K_FqupCMl
name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Archive project files
        run: zip -r project.zip dist/*

      - name: Upload to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.benzox.by
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /path/
